### PR TITLE
chore: satisfy clippy

### PR DESCRIPTION
**Pull request by rjzak**

### CODE REVIEW

**Comment by rjzak** [comment]
Some lines are changed due to my automatic use of `cargo fmt`, but I didn't add that as a linter since I don't know if that's something you care about.

**Comment by rjzak** [comment]
I don't know why the actions aren't running. But if there's an error, let me know and I'll fix it.

**Comment by rjzak** [comment]
@cccs-douglass Is your group open to receiving pull requests? Are there conditions/requirements? I'm excited about this functionality and would like to contribute!

**Comment by cccs-douglass** [comment]
Sorry, I got side tracked when I was reading the diff on this one. I'll circle back on this when I get my current task cleared out. In principle no problems with it.

**Comment by cccs-douglass** [comment]
I've refactored the layout of the library and in the process satisfied clippy (though not to the pedantic level) so I'm going to call this resolved.

**Pull request closed without merging**
